// packages/solid/src/CodexPet.tsx
import {
  createCodexPetRegistry,
  type CodexPetAnimationEvent,
  type CodexPetConfig,
  type CodexPetController,
  type CodexPetDragEvent,
  type CodexPetDragOptions,
  type CodexPetErrorEvent,
  type CodexPetFloatingOptions,
  type CodexPetId,
  type CodexPetManifest,
  type CodexPetState,
  type CodexPetStateChangeEvent,
  type CodexPetStateFps,
  type ReducedMotionPreference
} from "codex-pet-web";
import {
  createEffect,
  createMemo,
  onCleanup,
  splitProps,
  useContext,
  type JSX
} from "solid-js";
import { CodexPetRegistryContext } from "./context.jsx";

type NativeDivProps = Omit<
  JSX.HTMLAttributes<HTMLDivElement>,
  | "children"
  | "draggable"
  | "onAnimationStart"
  | "onAnimationEnd"
  | "onDrag"
  | "onDragStart"
  | "onDragEnd"
  | "onError"
>;

export interface CodexPetProps extends NativeDivProps {
  id?: CodexPetId;
  manifest?: CodexPetManifest;
  spritesheetUrl?: string;
  state?: CodexPetState;
  scale?: number;
  fps?: number;
  stateFps?: CodexPetStateFps;
  paused?: boolean;
  reducedMotion?: ReducedMotionPreference;
  imageRendering?: JSX.CSSProperties["image-rendering"];
  floating?: boolean | CodexPetFloatingOptions;
  draggable?: boolean | CodexPetDragOptions;
  preload?: boolean;
  onReady?: () => void;
  onError?: (event: CodexPetErrorEvent) => void;
  onStateChange?: (event: CodexPetStateChangeEvent) => void;
  onAnimationStart?: (event: CodexPetAnimationEvent) => void;
  onAnimationLoop?: (event: CodexPetAnimationEvent) => void;
  onAnimationEnd?: (event: CodexPetAnimationEvent) => void;
  onFrameChange?: (event: CodexPetAnimationEvent) => void;
  onPetDragStart?: (event: CodexPetDragEvent) => void;
  onPetDrag?: (event: CodexPetDragEvent) => void;
  onPetDragEnd?: (event: CodexPetDragEvent) => void;
}

function getDefinedConfig(
  config: Partial<CodexPetConfig>
): Partial<CodexPetConfig> {
  return Object.fromEntries(
    Object.entries(config).filter(([, value]) => value !== undefined)
  ) as Partial<CodexPetConfig>;
}

export function CodexPet(props: CodexPetProps): JSX.Element {
  const [local, divProps] = splitProps(props, [
    "id",
    "manifest",
    "spritesheetUrl",
    "state",
    "scale",
    "fps",
    "stateFps",
    "paused",
    "reducedMotion",
    "imageRendering",
    "floating",
    "draggable",
    "preload",
    "onReady",
    "onError",
    "onStateChange",
    "onAnimationStart",
    "onAnimationLoop",
    "onAnimationEnd",
    "onFrameChange",
    "onPetDragStart",
    "onPetDrag",
    "onPetDragEnd"
  ]);
  const contextRegistry = useContext(CodexPetRegistryContext);
  const petId = createMemo(() => local.id ?? local.manifest?.id ?? "default");
  const config = createMemo(() =>
    getDefinedConfig({
      spritesheetUrl: local.spritesheetUrl,
      state: local.state,
      scale: local.scale,
      fps: local.fps,
      stateFps: local.stateFps,
      paused: local.paused,
      reducedMotion: local.reducedMotion,
      imageRendering: String(local.imageRendering ?? "pixelated"),
      floating: local.floating,
      draggable:
        local.draggable && typeof local.draggable === "object"
          ? {
              ...local.draggable,
              onDragStart: (event) => {
                local.draggable && typeof local.draggable === "object"
                  ? local.draggable.onDragStart?.(event)
                  : undefined;
                local.onPetDragStart?.(event);
              },
              onDrag: (event) => {
                local.draggable && typeof local.draggable === "object"
                  ? local.draggable.onDrag?.(event)
                  : undefined;
                local.onPetDrag?.(event);
              },
              onDragEnd: (event) => {
                local.draggable && typeof local.draggable === "object"
                  ? local.draggable.onDragEnd?.(event)
                  : undefined;
                local.onPetDragEnd?.(event);
              }
            }
          : local.draggable
            ? {
                onDragStart: (event) => local.onPetDragStart?.(event),
                onDrag: (event) => local.onPetDrag?.(event),
                onDragEnd: (event) => local.onPetDragEnd?.(event)
              }
            : undefined,
      preload: local.preload,
      onReady: () => local.onReady?.(),
      onError: (event) => local.onError?.(event),
      onStateChange: (event) => local.onStateChange?.(event),
      onAnimationStart: (event) => local.onAnimationStart?.(event),
      onAnimationLoop: (event) => local.onAnimationLoop?.(event),
      onAnimationEnd: (event) => local.onAnimationEnd?.(event),
      onFrameChange: (event) => local.onFrameChange?.(event)
    })
  );
  const localRegistry =
    !contextRegistry && local.spritesheetUrl
      ? createCodexPetRegistry({
          defaultPetId: petId(),
          pets: {
            [petId()]: {
              ...config(),
              spritesheetUrl: local.spritesheetUrl
            }
          }
        })
      : null;
  const registry = contextRegistry ?? localRegistry;

  if (!registry) {
    throw new Error(
      "CodexPet requires spritesheetUrl when used without CodexPetProvider."
    );
  }

  const controller = createMemo<CodexPetController>(() =>
    registry.has(petId())
      ? registry.get(petId())
      : local.spritesheetUrl
        ? registry.register(petId(), {
            ...config(),
            spritesheetUrl: local.spritesheetUrl
          })
        : registry.get(petId())
  );
  let element: HTMLDivElement | undefined;
  let boundController: CodexPetController | null = null;

  createEffect(() => {
    controller().setConfig(config());
  });

  createEffect(() => {
    const nextController = controller();

    if (!element || boundController === nextController) {
      return;
    }

    boundController?.unbind(element);
    nextController.bind(element);
    boundController = nextController;
  });

  onCleanup(() => {
    boundController?.unbind(element);
  });

  return (
    <div
      {...divProps}
      aria-hidden={props["aria-label"] ? undefined : "true"}
      data-codex-pet={petId()}
      ref={element}
      role={props["aria-label"] ? "img" : divProps.role}
    />
  );
}

// packages/angular/src/codex-pet.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild
} from "@angular/core";
import {
  type CodexPetAnimationEvent,
  type CodexPetConfig,
  type CodexPetController,
  type CodexPetDragEvent,
  type CodexPetDragOptions,
  type CodexPetErrorEvent,
  type CodexPetFloatingOptions,
  type CodexPetId,
  type CodexPetManifest,
  type CodexPetState,
  type CodexPetStateChangeEvent,
  type CodexPetStateFps,
  type ReducedMotionPreference
} from "codex-pet-web";
import { CodexPetRegistryService } from "./codex-pet-registry.service";

function getDefinedConfig(
  config: Partial<CodexPetConfig>
): Partial<CodexPetConfig> {
  return Object.fromEntries(
    Object.entries(config).filter(([, value]) => value !== undefined)
  ) as Partial<CodexPetConfig>;
}

@Component({
  selector: "codex-pet",
  standalone: true,
  template: `
    <div
      #host
      [attr.aria-hidden]="ariaLabel ? null : 'true'"
      [attr.aria-label]="ariaLabel || null"
      [attr.data-codex-pet]="petId"
      [attr.role]="ariaLabel ? 'img' : null"
    ></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CodexPetComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() id?: CodexPetId;
  @Input() manifest?: CodexPetManifest;
  @Input() spritesheetUrl?: string;
  @Input() state?: CodexPetState;
  @Input() scale?: number;
  @Input() fps?: number;
  @Input() stateFps?: CodexPetStateFps;
  @Input() paused?: boolean;
  @Input() reducedMotion?: ReducedMotionPreference;
  @Input() imageRendering = "pixelated";
  @Input() floating?: boolean | CodexPetFloatingOptions;
  @Input() draggable?: boolean | CodexPetDragOptions;
  @Input() preload?: boolean;
  @Input() ariaLabel?: string;

  @Output() ready = new EventEmitter<void>();
  @Output() petError = new EventEmitter<CodexPetErrorEvent>();
  @Output() stateChange = new EventEmitter<CodexPetStateChangeEvent>();
  @Output() animationStart = new EventEmitter<CodexPetAnimationEvent>();
  @Output() animationLoop = new EventEmitter<CodexPetAnimationEvent>();
  @Output() animationEnd = new EventEmitter<CodexPetAnimationEvent>();
  @Output() frameChange = new EventEmitter<CodexPetAnimationEvent>();
  @Output() petDragStart = new EventEmitter<CodexPetDragEvent>();
  @Output() petDrag = new EventEmitter<CodexPetDragEvent>();
  @Output() petDragEnd = new EventEmitter<CodexPetDragEvent>();

  @ViewChild("host", { static: true })
  private host?: ElementRef<HTMLDivElement>;

  private controller?: CodexPetController;
  private boundElement?: HTMLDivElement;

  constructor(private readonly pets: CodexPetRegistryService) {}

  get petId(): CodexPetId {
    return this.id ?? this.manifest?.id ?? "default";
  }

  ngAfterViewInit(): void {
    this.bind();
  }

  ngOnChanges(_changes: SimpleChanges): void {
    if (!this.controller) {
      return;
    }

    this.controller.setConfig(this.getConfig());
  }

  ngOnDestroy(): void {
    this.controller?.unbind(this.boundElement);
  }

  private bind(): void {
    const element = this.host?.nativeElement;

    if (!element) {
      return;
    }

    this.controller = this.resolveController();
    this.boundElement = element;
    this.controller.bind(element);
  }

  private resolveController(): CodexPetController {
    const petId = this.petId;

    if (this.pets.registry.has(petId)) {
      return this.pets.get(petId);
    }

    if (!this.spritesheetUrl) {
      return this.pets.get(petId);
    }

    return this.pets.register(petId, {
      ...this.getConfig(),
      spritesheetUrl: this.spritesheetUrl
    });
  }

  private getConfig(): Partial<CodexPetConfig> {
    return getDefinedConfig({
      spritesheetUrl: this.spritesheetUrl,
      state: this.state,
      scale: this.scale,
      fps: this.fps,
      stateFps: this.stateFps,
      paused: this.paused,
      reducedMotion: this.reducedMotion,
      imageRendering: this.imageRendering,
      floating: this.floating,
      draggable: this.getDragConfig(),
      preload: this.preload,
      onReady: () => this.ready.emit(),
      onError: (event: CodexPetErrorEvent) => this.petError.emit(event),
      onStateChange: (event: CodexPetStateChangeEvent) =>
        this.stateChange.emit(event),
      onAnimationStart: (event: CodexPetAnimationEvent) =>
        this.animationStart.emit(event),
      onAnimationLoop: (event: CodexPetAnimationEvent) =>
        this.animationLoop.emit(event),
      onAnimationEnd: (event: CodexPetAnimationEvent) =>
        this.animationEnd.emit(event),
      onFrameChange: (event: CodexPetAnimationEvent) =>
        this.frameChange.emit(event)
    });
  }

  private getDragConfig(): boolean | CodexPetDragOptions | undefined {
    if (!this.draggable) {
      return undefined;
    }

    const userOptions =
      typeof this.draggable === "object" ? this.draggable : undefined;

    return {
      ...userOptions,
      onDragStart: (event: CodexPetDragEvent) => {
        userOptions?.onDragStart?.(event);
        this.petDragStart.emit(event);
      },
      onDrag: (event: CodexPetDragEvent) => {
        userOptions?.onDrag?.(event);
        this.petDrag.emit(event);
      },
      onDragEnd: (event: CodexPetDragEvent) => {
        userOptions?.onDragEnd?.(event);
        this.petDragEnd.emit(event);
      }
    };
  }
}
