// packages/solid/src/useCodexPetRandomActions.ts
import {
  createCodexPetRandomActionRunner,
  type CodexPetId,
  type CodexPetRandomActionRunnerOptions
} from "codex-pet-web";
import { createEffect, onCleanup } from "solid-js";
import { useCodexPet } from "./context.jsx";

export function useCodexPetRandomActions(
  id: CodexPetId | undefined,
  options: CodexPetRandomActionRunnerOptions
): void {
  const pet = useCodexPet(id);

  createEffect(() => {
    const runner = createCodexPetRandomActionRunner(pet, options);
    runner.start();

    onCleanup(() => {
      runner.destroy();
    });
  });
}

// packages/react/src/useCodexPetRandomActions.ts
import {
  createCodexPetRandomActionRunner,
  type CodexPetId,
  type CodexPetRandomActionRunnerOptions
} from "codex-pet-web";
import { useEffect } from "react";
import { useCodexPet } from "./CodexPetProvider.js";

export function useCodexPetRandomActions(
  id: CodexPetId | undefined,
  options: CodexPetRandomActionRunnerOptions
): void {
  const pet = useCodexPet(id);

  useEffect(() => {
    const runner = createCodexPetRandomActionRunner(pet, options);
    runner.start();

    return () => {
      runner.destroy();
    };
  }, [pet, options]);
}
